subnets:
  - name: subnet01
    cidr: 10.0.0.0/24
    region: asia-south2
    network:
      name:
        selfLink: "https://www.googleapis.com/compute/v1/projects/cogent-tide-366115/global/networks/homelab-vpc01"
    secondary_ip_ranges:
      - ip_cidr_range: 10.0.3.0/21
        range_name: "pods-subnet01"
      - ip_cidr_range: 10.0.5.0/21
        range_name: "services-subnet01"

  - name: subnet02
    cidr: 10.2.0.0/24
    region: europe-west4
    network:
      name:
        selfLink: "https://www.googleapis.com/compute/v1/projects/cogent-tide-366115/global/networks/homelab-vpc02"
    secondary_ip_ranges:
      - ip_cidr_range: 10.0.4.0/21
        range_name: "pods-subnet02"
      - ip_cidr_range: 10.0.6.0/21
        range_name: "services-subnet02"
